"""empty message

Revision ID: 003d9bbb3d44
Revises: 0d41bcca000a
Create Date: 2021-03-09 18:48:22.718327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003d9bbb3d44'
down_revision = '0d41bcca000a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lendings', sa.Column('is_confirming_returned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lendings', 'is_confirming_returned')
    # ### end Alembic commands ###
