"""empty message

Revision ID: 1954c2e17af8
Revises: 8ea66adb0eaf
Create Date: 2021-03-03 02:35:04.291579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1954c2e17af8'
down_revision = '8ea66adb0eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comment')
    # ### end Alembic commands ###
