"""empty message

Revision ID: 1e13dfec183c
Revises: 1954c2e17af8
Create Date: 2021-03-03 02:44:06.499839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e13dfec183c'
down_revision = '1954c2e17af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
