"""empty message

Revision ID: 33d7107d1c4a
Revises: 1f2336e006bf
Create Date: 2021-03-12 06:08:28.130830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7107d1c4a'
down_revision = '1f2336e006bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lendings', sa.Column('is_sent_url', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lendings', 'is_sent_url')
    # ### end Alembic commands ###
