@startuml er

hide circle
skinparam inetype ortho

entity User {
    +id: string
    --
    name: string
    picture_url: string
    status_message: string
}

entity Lending {
    +id: int <<AUTO INCREMENT>>
    --
    ~owner_id: string <<FK>>
    ~borrower_id: string <<FK>>
    #content: string
    #deadline: Datetime
}

User }--o{ Lending

entity Example {
    +primary_key: type
    ~foreign_key: type
    #not null: type  
}
note bottom of Example: 上からそれぞれ<<PK>>, <<FK>>, <<NOT NULL>>を表す記号

@enduml
