@startuml sequence
actor       "貸す人（Aさん）"      as usera
participant "LINE Bot（Aさん側）" as bota
participant "LIFF(React)（Aさん側）" as liffa
participant "サーバー" as server
participant "LINE Platform" as platform
participant "LIFF（Bさん側）" as liffb
participant "LINE Bot（Bさん側）" as botb
actor "借りる人（Bさん）" as userb

bota -> usera: RichMenu内でURLを表示

== 貸す側の手続き ==
usera -> liffa: サービスにアクセス
liffa -> liffa: ユーザー情報（アクセストークン）を取得
usera -> liffa: 貸す物を選択/期限などを入力
liffa -> server ++: 貸出情報（貸す物/期限など）を送信
opt トークン検証
  server -> platform: アクセストークンを検証
  platform -> server: 検証結果
end
server -> platform: ユーザー情報（userId）をリクエスト
platform -> server: ユーザー情報（userId）
server -> server: 貸出情報を保存
server -> liffa --: 貸出トークン?（貸出ID？）
usera -> liffa: 貸す相手を選択
liffa -> platform: 貸出トークン付きURLをBさんに送信（shareTargetPicker）
platform -> userb: Aさんに代わってURLを（AさんとBさんの間の個人チャットに）送信
liffa -> usera: Botを友達登録していない場合は登録を促す

== 借りる側の手続き ==
userb -> liffb: 届いたURLにアクセス
liffb -> liffb: ユーザー情報（アクセストークン）を取得
liffb -> liffb: URLから貸出トークンを取得
opt 貸出同意画面（今回は優先順位低）
  liffb -> server ++: 貸出トークンを送信
  server -> liffb --: （Aさんが登録した）貸出情報を取得
  liffb -> userb: 貸出情報を表示
  userb -> liffb: 貸出に同意
end
liffb -> server ++: 貸出トークン（貸出ID）を送信
server <-> platform: [略]アクセストークン検証とユーザー情報取得
server -> server: 貸出IDを元に貸出情報とBさんを紐付け
opt 優先順位低
  server -> bota: 貸出処理完了通知
end
server -> liffb --: 貸出処理成功・お礼のリコメンド
liffb -> userb: お礼の候補を提案する
liffb -> userb: Botを友達登録していない場合は登録を促す

== 返却日のリマインド（botが聞くパターン） ==
server -> bota: 返却済みか確認するメッセージ
bota -> usera: 返却済みか確認
alt 返却済みの場合
  usera -> bota: 返却済みボタンをタップ
  bota -> server ++: 返却済み
  server -> server: 返却完了処理
  opt 優先順位低
    server -> botb --: 返却処理の完了通知（お礼の提案）
  end
else 返却がまだの場合
  usera -> bota: 返却まだボタンをタップ
  bota -> server: 返却まだ
  loop 定期リマインド
    server -> botb: リマインド
  end
end

== 返却終了（ユーザーから登録パターン） ==
usera -> liffa: 返却報告
liffa -> server: 返却報告
server -> server: 返却完了処理
server -> botb: 返却処理の完了通知（お礼の提案）

@enduml